name: Deploy Next.js to JSC-VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --pull -t nextjs-app:latest .

      - name: Save Docker image
        run: docker save nextjs-app:latest > nextjs-app.tar

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JSC_HOST }}
          username: ${{ secrets.JSC_USER }}
          key: ${{ secrets.JSC_SSH_KEY }}
          port: ${{ secrets.JSC_PORT }}
          source: "nextjs-app.tar"
          target: "~/"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JSC_HOST }}
          username: ${{ secrets.JSC_USER }}
          key: ${{ secrets.JSC_SSH_KEY }}
          port: ${{ secrets.JSC_PORT }}
          script: |
            docker image prune -f || true

            docker load < nextjs-app.tar

            docker stop nextjs-container || true
            docker rm nextjs-container || true

            docker run -d \
              --name nextjs-container \
              -p 3000:3000 \
              --restart unless-stopped \
              nextjs-app:latest
